logging:
  level:
    org.springframework.web.servlet: INFO
spring:
  datasource:
    url: "jdbc:postgresql_postGIS://localhost/seb"
    username: "postgres"
  mvc:
      async:
        request-timeout: 1000000