spring:
  datasource:
    platform: "postgres"
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "bernat.borras"
  mvc:
      async:
        request-timeout: 1000000